---
title: "PE"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(ecofolio)
knitr::opts_chunk$set(echo = TRUE)
col<- c("#000000", "#FF0000")
load("/media/hdd/mbuoro/MetaIBASAM/analysis/30Simul/PE.Rdata")
nSIMUL <- 30
```

## R Markdown

```{r trend, echo=FALSE}

## Popualtions trend

plot(NULL, xlim=c(0,50), ylim=c(0, 200))
j=10
for (i in 1:16){ # loop over simulations
lines(1:50, nReturns$`11`[[j]][,i], col=paste0(col[1],"25"))
#lines(1:50, nReturns$`12`[[j]][,i], col=paste0(col[2],"25"))
# 
# lines(1:50, nReturns$`21`[[j]][,i], col=paste0(col[1],"50"))
# lines(1:50, nReturns$`22`[[j]][,i], col=paste0(col[2],"50"))
# 
# lines(1:50, nReturns$`31`[[j]][,i], col=paste0(col[1],"90"))
# lines(1:50, nReturns$`32`[[j]][,i], col=paste0(col[2],"90"))
}
```

```{r trend2, echo=FALSE}

## Popualtions trend

plot(NULL, xlim=c(0,50), ylim=c(0, 200))
for (j in 1:nSIMUL){ # loop over simulations
lines(1:50, nReturns$`11`[[j]][,1], col=paste0(col[1],"25"))
lines(1:50, nReturns$`12`[[j]][,1], col=paste0(col[2],"25"))

lines(1:50, nReturns$`21`[[j]][,1], col=paste0(col[1],"50"))
lines(1:50, nReturns$`22`[[j]][,1], col=paste0(col[2],"50"))

lines(1:50, nReturns$`31`[[j]][,1], col=paste0(col[1],"90"))
lines(1:50, nReturns$`32`[[j]][,1], col=paste0(col[2],"90"))
}
```


```{r pe, echo=FALSE}
gap=c(-.1,.1)
i=4
plot(NULL, xlim=c(0.5,3.5),ylim=c(.5,3),ylab="Portfolio effect")
# for (j in 1:nSIMUL) points(1+gap[1],PE$`11`[j,2],pch=16,col=1)
# for (j in 1:nSIMUL) points(1+gap[2],PE$`12`[j,2],pch=16,col=paste0(col[2],"25"))
# 
# for (j in 1:nSIMUL) points(2+gap[1],PE$`21`[j,2],pch=16,col=1)
# for (j in 1:nSIMUL) points(2+gap[2],PE$`22`[j,2],pch=16,col=paste0(col[2],"25"))
# 
# for (j in 1:nSIMUL) points(3+gap[1],PE$`31`[j,2],pch=16,col=1)
# for (j in 1:nSIMUL) points(3+gap[2],PE$`32`[j,2],pch=16,col=paste0(col[2],"25"))

segments(1+gap[1],apply(PE$`11`,2,quantile,probs=.025)[i], 1+gap[1],apply(PE$`11`,2,quantile,probs=.975)[i], col=paste0(col[1],"25"))
segments(2+gap[1],apply(PE$`21`,2,quantile,probs=.025)[i], 2+gap[1],apply(PE$`21`,2,quantile,probs=.975)[i], col=paste0(col[1],"50"))
segments(3+gap[1],apply(PE$`31`,2,quantile,probs=.025)[i], 3+gap[1],apply(PE$`31`,2,quantile,probs=.975)[i], col=paste0(col[1],"90"))
points(1+gap[1],apply(PE$`11`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"25"))
points(2+gap[1],apply(PE$`21`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"50"))
points(3+gap[1],apply(PE$`31`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"90"))

segments(1+gap[2],apply(PE$`12`,2,quantile,probs=.025)[i], 1+gap[2],apply(PE$`12`,2,quantile,probs=.975)[i], col=paste0(col[2],"25"))
segments(2+gap[2],apply(PE$`22`,2,quantile,probs=.025)[i], 2+gap[2],apply(PE$`22`,2,quantile,probs=.975)[i], col=paste0(col[2],"50"))
segments(3+gap[2],apply(PE$`32`,2,quantile,probs=.025)[i], 3+gap[2],apply(PE$`32`,2,quantile,probs=.975)[i], col=paste0(col[2],"90"))
points(1+gap[2],apply(PE$`12`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"25"))
points(2+gap[2],apply(PE$`22`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"50"))
points(3+gap[2],apply(PE$`32`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"90"))
```

```{r synchrony, echo=FALSE}
gap=c(-.1,.1)
i=7 # synchony
plot(NULL, xlim=c(0.5,3.5),ylim=c(0,1),ylab="Synchrony")
abline(h=.6, lty=2)
# for (j in 1:nSIMUL) points(1+gap[1],PE$`11`[j,3],pch=16,col=1)
# for (j in 1:nSIMUL) points(1+gap[2],PE$`12`[j,3],pch=16,col=paste0(col[2],"25"))
# 
# for (j in 1:nSIMUL) points(2+gap[1],PE$`21`[j,3],pch=16,col=1)
# for (j in 1:nSIMUL) points(2+gap[2],PE$`22`[j,3],pch=16,col=paste0(col[2],"25"))
# 
# for (j in 1:nSIMUL) points(3+gap[1],PE$`31`[j,3],pch=16,col=1)
# for (j in 1:nSIMUL) points(3+gap[2],PE$`32`[j,3],pch=16,col=paste0(col[2],"25"))
segments(1+gap[1],apply(PE$`11`,2,quantile,probs=.025)[i], 1+gap[1],apply(PE$`11`,2,quantile,probs=.975)[i], col=paste0(col[1],"25"))
segments(2+gap[1],apply(PE$`21`,2,quantile,probs=.025)[i], 2+gap[1],apply(PE$`21`,2,quantile,probs=.975)[i], col=paste0(col[1],"50"))
segments(3+gap[1],apply(PE$`31`,2,quantile,probs=.025)[i], 3+gap[1],apply(PE$`31`,2,quantile,probs=.975)[i], col=paste0(col[1],"90"))
points(1+gap[1],apply(PE$`11`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"25"))
points(2+gap[1],apply(PE$`21`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"50"))
points(3+gap[1],apply(PE$`31`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[1],"90"))

segments(1+gap[2],apply(PE$`12`,2,quantile,probs=.025)[i], 1+gap[2],apply(PE$`12`,2,quantile,probs=.975)[i], col=paste0(col[2],"25"))
segments(2+gap[2],apply(PE$`22`,2,quantile,probs=.025)[i], 2+gap[2],apply(PE$`22`,2,quantile,probs=.975)[i], col=paste0(col[2],"50"))
segments(3+gap[2],apply(PE$`32`,2,quantile,probs=.025)[i], 3+gap[2],apply(PE$`32`,2,quantile,probs=.975)[i], col=paste0(col[2],"90"))
points(1+gap[2],apply(PE$`12`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"25"))
points(2+gap[2],apply(PE$`22`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"50"))
points(3+gap[2],apply(PE$`32`,2,quantile,probs=.5)[i], pch=16, cex=2,col=paste0(col[2],"90"))
```

```{r pe_plot, echo=FALSE}
pe.pred <- function(x){
  m <- apply(x,2,mean)
  v <- apply(x,2,var)
  mv <- data.frame(m=(m), v=(v))
  
overall.d <- apply(x, 1, sum)
overall.mean <- mean(overall.d, na.rm = TRUE)
portfolio.var <- var(overall.d, na.rm = TRUE)
m.t <- lm(log(v) ~ log(m), data = mv)
overall.variance <- exp(as.numeric(predict(m.t, newdata =data.frame(m = overall.mean))))

d1p <- seq(min(mv$m), max(mv$m), length.out = 200)
d2p <- seq(max(mv$m), overall.mean, length.out = 200)

m.t.p <- predict(m.t, newdata = data.frame(m = seq(min(mv$m),
                                                   max(mv$m), length.out = 2)))
m.t.p2 <- predict(m.t, newdata = data.frame(m = seq(max(mv$m),
                                                    overall.mean, length.out = 2)))
p1 <- predict(m.t, newdata = data.frame(m = d1p), se = TRUE)
p2 <- predict(m.t, newdata = data.frame(m = d2p), se = TRUE)

return(list(m=(m), v=(v), portfolio.var=portfolio.var,
            overall.mean=(overall.mean)
            ,overall.variance=(overall.variance)
            ,m.t.p=m.t.p,m.t.p2=m.t.p2
            ,z=round(coef(m.t)[2], 2)))
}

RES=list()

par(mfrow=c(1,2))

plot(NULL,xlim=c(20,3000),ylim=c(20,450000),xlab = "log(mean)", ylab ="log(variance)",log="xy")
i = sample(1:nSIMUL,1)
res <- pe.pred(nReturns$`11`[[i]])
RES[["11"]]<-res
points((res$m), (res$v), pch=16, col=paste0(col[1],"25"))
#abline(lm(log(v) ~ log(m), data=res), col="blue")
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[1],"25"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[1],"25"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[1],"25"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[1],"25"),cex=.8)
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -1.5, col = paste0(col[1],"25"))
mtext(paste0("sync =", round(PE$`11`[1,"sync"],2)), side = 1, adj = 0.7, line = -1.5, col = paste0(col[1],"25"),cex=.8)
mtext(paste0("PE =", round(PE$`11`[1,"petr"],2)), side = 1, adj = 0.5, line = -1.5, col = paste0(col[1],"25"),cex=.8)



res <- pe.pred(nReturns$`21`[[i]])
RES[["21"]]<-res
points((res$m), (res$v), pch=16, col=paste0(col[1],"50"))
#abline(lm(log(v) ~ log(m), data=res), col="blue")
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[1],"50"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[1],"50"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[1],"50"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[1],"50"),cex=.8)
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -2.5, col = paste0(col[1],"50"))
mtext(paste0("sync =", round(PE$`21`[1,"sync"],2)), side = 1, adj = 0.7, line = -2.5, col = paste0(col[1],"50"),cex=.8)
mtext(paste0("PE =", round(PE$`21`[1,"petr"],2)), side = 1, adj = 0.5, line = -2.5, col = paste0(col[1],"50"),cex=.8)



res <- pe.pred(nReturns$`31`[[i]])
RES[["31"]]<-res
points((res$m), (res$v), pch=16, col=paste0(col[1],"90"))
#abline(lm(log(v) ~ log(m), data=res), col="blue")
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[1],"90"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[1],"90"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[1],"90"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[1],"90"),cex=.8)
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -3.5, col = paste0(col[1],"90"))
mtext(paste0("sync =", round(PE$`31`[1,"sync"],2)), side = 1, adj = 0.7, line = -3.5, col = paste0(col[1],"90"),cex=.8)
mtext(paste0("PE =", round(PE$`31`[1,"petr"],2)), side = 1, adj = 0.5, line = -3.5, col = paste0(col[1],"90"),cex=.8)









plot(NULL,xlim=c(20,3000),ylim=c(20,450000),xlab = "log(mean)", ylab ="log(variance)",log="xy")
i = sample(1:nSIMUL,1)

res <- pe.pred(nReturns$`12`[[i]])
RES[["12"]]<-res
points(res$m, res$v, pch=16, col=paste0(col[2],"25"))
#abline(lm(log(v) ~ log(m), data=res), col=paste0(col[2],"25"))
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[2],"25"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[2],"25"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[2],"25"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[2],"25"))
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -1, col = paste0(col[2],"25"),cex=.8)
mtext(paste0("sync =", round(PE$`12`[1,"sync"],2)), side = 1, adj = 0.7, line = -1, col = paste0(col[2],"25"),cex=.8)
mtext(paste0("PE =", round(PE$`12`[1,"petr"],2)), side = 1, adj = 0.5, line = -1, col = paste0(col[2],"25"),cex=.8)


res <- pe.pred(nReturns$`22`[[i]])
RES[["22"]]<-res
points(res$m, res$v, pch=16, col=paste0(col[2],"50"))
#abline(lm(log(v) ~ log(m), data=res), col=paste0(col[2],"25"))
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[2],"50"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[2],"50"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[2],"50"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[2],"25"))
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -2, col = paste0(col[2],"50"),cex=.8)
mtext(paste0("sync =", round(PE$`22`[1,"sync"],2)), side = 1, adj = 0.7, line = -2, col = paste0(col[2],"50"),cex=.8)
mtext(paste0("PE =", round(PE$`22`[1,"petr"],2)), side = 1, adj = 0.5, line = -2, col = paste0(col[2],"50"),cex=.8)



res <- pe.pred(nReturns$`32`[[i]])
RES[["32"]]<-res
points(res$m, res$v, pch=16, col=paste0(col[2],"90"))
#abline(lm(log(v) ~ log(m), data=res), col=paste0(col[2],"25"))
#points(res$M, res$V, pch=21, col="blue")
points((res$overall.mean), (res$portfolio.var), col = paste0(col[2],"90"), pch = 4, lwd= 1.2, cex = 1.6)
points((res$overall.mean), (res$overall.variance), col = paste0(col[2],"90"), pch = 1, lwd = 1.5, cex = 1.4)
segments((min(res$m)), exp(res$m.t.p[1]), (max(res$m)), exp(res$m.t.p[2]),col = paste0(col[2],"90"), lty = 1)
segments((max(res$m)), exp(res$m.t.p2[1]), (res$overall.mean),exp(res$m.t.p2[2]), lty = 2,  col = paste0(col[2],"90"))
mtext(paste0("z =", res$z), side = 1, adj = 0.9, line = -3, col = paste0(col[2],"90"),cex=.8)
mtext(paste0("sync =", round(PE$`32`[1,"sync"],2)), side = 1, adj = 0.7, line = -3, col = paste0(col[2],"90"),cex=.8)
mtext(paste0("PE =", round(PE$`32`[1,"petr"],2)), side = 1, adj = 0.5, line = -3, col = paste0(col[2],"90"),cex=.8)

```

